name       : libjson-glib
version    : 1.0.4
release    : 8
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/json-glib/1.0/json-glib-1.0.4.tar.xz : 80f3593cb6bd13f1465828e46a9f740e2e9bd3cd2257889442b3e62bd6de05cd
homepage   : https://live.gnome.org/JsonGlib
license    :
    - LGPL-2.0
summary    : JSON GLib Package
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
