name       : libjson-glib
version    : 1.6.2
release    : 20
source     :
    - git|https://gitlab.gnome.org/GNOME/json-glib.git : 02960c35c41beda47f3d590202b7bcc9f53cb2bf
homepage   : https://live.gnome.org/JsonGlib
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : JSON GLib Package
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
