name       : libjson-glib
version    : 1.2.2
release    : 10
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/json-glib/1.2/json-glib-1.2.2.tar.xz : ea128ab52a824fcd06e5448fbb2bd8d9a13740d51c66d445828edba71321a621
homepage   : https://live.gnome.org/JsonGlib
license    :
    - LGPL-2.0
summary    : JSON GLib Package
component  : desktop.gnome.core
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
