name       : libjson-glib
version    : 1.2.8
release    : 11
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/json-glib/1.2/json-glib-1.2.8.tar.xz : fd55a9037d39e7a10f0db64309f5f0265fa32ec962bf85066087b83a2807f40a
homepage   : https://live.gnome.org/JsonGlib
license    :
    - LGPL-2.0
summary    : JSON GLib Package
component  : desktop.gnome.core
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
