name       : libjson-glib
version    : 1.6.6
release    : 23
source     :
    - https://download.gnome.org/sources/json-glib/1.6/json-glib-1.6.6.tar.xz : 96ec98be7a91f6dde33636720e3da2ff6ecbb90e76ccaa49497f31a6855a490e
homepage   : https://live.gnome.org/JsonGlib
license    : LGPL-2.0-only
component  : system.base
summary    : JSON GLib Package
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
