name        : libjson-glib
version     : 1.0.4
release     : 7
source      :
    - http://ftp.gnome.org/pub/GNOME/sources/json-glib/1.0/json-glib-1.0.4.tar.xz : 80f3593cb6bd13f1465828e46a9f740e2e9bd3cd2257889442b3e62bd6de05cd
homepage    : https://live.gnome.org/JsonGlib
license     :
    - LGPL-2.0
summary     : JSON GLib Package
description : |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
