name       : libjson-glib
version    : 1.4.2
release    : 14
source     :
    - https://download.gnome.org/sources/json-glib/1.4/json-glib-1.4.2.tar.xz : 2d7709a44749c7318599a6829322e081915bdc73f5be5045882ed120bb686dc8
homepage   : https://live.gnome.org/JsonGlib
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : JSON GLib Package
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure
build      : |
    export LC_ALL=en_US.utf8
    %ninja_build
install    : |
    export LC_ALL=en_US.utf8
    %ninja_install
