name       : libjson-glib
version    : 1.4.2
release    : 12
source     :
    - https://download.gnome.org/sources/json-glib/1.4/json-glib-1.4.2.tar.xz : 2d7709a44749c7318599a6829322e081915bdc73f5be5045882ed120bb686dc8
homepage   : https://live.gnome.org/JsonGlib
license    :
    - LGPL-2.0
summary    : JSON GLib Package
component  : desktop.gnome.core
builddeps  :
    - pkgconfig32(gio-unix-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure
build      : |
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
