name       : libjson-glib
version    : 1.6.2
release    : 19
source     :
    - https://download.gnome.org/sources/json-glib/1.6/json-glib-1.6.2.tar.xz : a33d66c6d038bda46b910c6c6d59c4e15db014e363dc997a0414c2e07d134f24
homepage   : https://live.gnome.org/JsonGlib
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : JSON GLib Package
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
