name       : libjson-glib
version    : 1.4.4
release    : 17
source     :
    - https://download.gnome.org/sources/json-glib/1.4/json-glib-1.4.4.tar.xz : 720c5f4379513dc11fd97dc75336eb0c0d3338c53128044d9fabec4374f4bc47
homepage   : https://live.gnome.org/JsonGlib
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : JSON GLib Package
description: |
    The JSON GLib package is a library providing serialization and deserialization support for the JavaScript Object Notation (JSON) format described by RFC 4627.
emul32     : yes
builddeps  :
    - pkgconfig32(gio-unix-2.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
